language: java
jdk:
  - openjdk16

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r sciencemj-chatting *
  - mkdir -p deploy
  - mv sciencemj-chatting.zip deploy/sciencemj-chatting.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: sciencemj-chat-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-untill-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sciencemj-chat-build
    key: sciencemj-chatting.zip
    bundle_type: zip
    application: sciencemj-chatting
    deployment_group: sciencemj-chatting-group
    region: ap-northeast-2
    wait-untill-deployed: true
notifications:
  email:
    recipients:
      - sciencemj.park@gmail.com